apiVersion: v1
kind: Service
metadata:
  name: central-api-service
  namespace: kube-system
spec:
  type: NodePort  # 외부 접근 가능하게 설정
  selector:
    app: central-api-server
  ports:
    - port: 8082
      targetPort: 8082
      nodePort: 30082  # VM 외부에서 접근 가능한 포트
